[package]
name = "vk-voxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.32.3"
vulkano-win = "0.32.0"
winit = "0.27.5"
